apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ci-dashboard-chart.fullname" . }}
  labels:
    {{- include "ci-dashboard-chart.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "ci-dashboard-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
